### ISSUE TITLE
Projects: GitHub API consensus

### ISSUE THREAD

**Issue by rkzel** [spacedecentral/planning-suite#201]
Two decisions to be made:

1. Apollo vs previous graphql client. Some more reading is required, but Apollo is more powerful and if current configuration is working, it should stay.

2. What credentials should we use for communicating with GitHub exactly? Original idea was for users to have individual accounts and tokens. That approach avoids necessity for some centralized credentials storage required for OAuth to work. On the other hand if a DAO should be able to automatically manipulate things in GitHub (like create issues, add labels, etc, when a vote is concluded) the personal token is not sufficient.

**Comment by stellarmagnet** [comment]
Did we decide on the App approach?

**Comment by Quazia** [comment]
The app approach has been implemented I'm closing this issue
