### ISSUE TITLE
Deploy M2 to Rinkeby

### ISSUE THREAD

**Issue by Quazia** [spacedecentral/planning-suite#250]
Should be trivial. Once everything is in a demo-able state I'll try and address this.

**Comment by sohkai** [comment]
@Quazia let us know if something's not working. Once you've adjusted to the new [`environment` format for the `arapp.json`](https://github.com/aragon/aragon-apps/blob/master/apps/finance/arapp.json#L1), it should be pretty straightforward, I hope!

**Comment by stellarmagnet** [comment]
Closing this issue, as we don't need an issue to track it...
