### ISSUE TITLE
Projects app - toolbar component to search and filter issues

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/planning-suite#266]
This encompasses the front-end and the backend/Github API logic to properly search and filter issues in the Projects app.

**Comment by topocount** [comment]
Currently researching this. I know @rkzel wants to take a shot at this, so I'm happy to yield if he can make progress.

**Comment by stellarmagnet** [comment]
This was never fully completed. We have to remove the features that aren't fully baked. Closing this for now. See #389
