### ISSUE TITLE
Range voting status says "Ongoing" for closed votes

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/planning-suite#300]
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/b0bac9dc-c530-4cd2-8f43-70ae84adab1c)

**Comment by topocount** [comment]
This actually updates to say "Timeout" If the vote is clicked and the rangevoting sidebar is opened

**Comment by stellarmagnet** [comment]
> This actually updates to say "Timeout" when the vote is clicked and the rangevoting sidebar is opened.
> **EDIT**: Haven't been able to reliably replicate this observation

This probably happens bc the vote lasts one minute - a bit unrelated

**Comment by stellarmagnet** [comment]
Closing this issue, as it's a duplicate of #204 essentially
